### PR TITLE
Images From Chromecast Background Update

### PR DESCRIPTION
**Pull request by TheLukaBoss**
Please read [this feature request for info](https://github.com/kolbyjack/MMM-Wallpaper/issues/11).

### CODE REVIEW

**Comment by TheLukaBoss** [comment]
Upon merging (if you do), you will need to alter the Installation instructions, as I have changed them to suit this repo.

**Comment by kolbyjack** [comment]
Implemented a slightly different way in 16c6973

**Comment by TheLukaBoss** [comment]
> Implemented a slightly different way in [16c6973](https://github.com/kolbyjack/MMM-Wallpaper/commit/16c6973381518eaa486e05b6abcf791c8fb515cb)

Thanks! By the way, you forgot to update the readme. 😁

**Comment by TheLukaBoss** [comment]
Yay! Thanks!

**Pull request closed without merging**
